### ISSUE TITLE
Add non BORE linux-cachyos

### ISSUE THREAD

**Issue by ptr1337** [sirlucjan/copr-linux-cachyos#10]
We got in the discord some reports, that the BORE variant freezes, when shutting down the laptop.

Lets add another Variant, for example linux-cachyos-eevdf or linux-cachyos-sched-ext, which does not include BORE.

**Comment by 1Naim** [comment]
i'm the one who made one of these reports, and have concluded that the issue was not on BORE's end.

Trixie has also made a [copr](https://copr.fedorainfracloud.org/coprs/trixieua/kernel-cachyos-nobore/) for non-BORE and it may or may not be deleted in the future.

the original purpose of this issue has been fulfilled and i think this issue can be closed. Although if the copr maintainers are interested in adding other variants of the cachyos kernel to the copr, this issue can be left open.

**Comment by andersrh** [comment]
Hi @1Naim 

thanks for your update.
I'm actually interested in adding sched-ext. Trixie experimented with it, but had some issues last time.

**Comment by ptr1337** [comment]
> Hi @1Naim
> 
> thanks for your update. I'm actually interested in adding sched-ext. Trixie experimented with it, but had some issues last time.

There is a sched-ext fedora/copr maintainer. The kernel itself should be ready fine for 6.9.
the scx-scheds package we can add to the copr, i guess.
linux-cachyos contains as default sched-ext (not sure about the copr here, but it should)

**Comment by andersrh** [comment]
> > Hi @1Naim
> > 
> > thanks for your update. I'm actually interested in adding sched-ext. Trixie experimented with it, but had some issues last time.
> 
> There is a sched-ext fedora/copr maintainer. The kernel itself should be ready fine for 6.9.
> the scx-scheds package we can add to the copr, i guess.
> linux-cachyos contains as default sched-ext (not sure about the copr here, but it should)

The problem we had last time was that the kernel-modules package ended up being 2 GB in size.

So in order to have sched-ext in the kernel, it needs to include this patch? https://github.com/CachyOS/kernel-patches/blob/master/6.9/sched/0001-sched-ext-eevdf.patch
Or is it there without it?

Currently we include 0001-cachyos-base-all.patch and 0001-bore-cachy.patch

**Comment by ptr1337** [comment]
> > > Hi @1Naim
> > > thanks for your update. I'm actually interested in adding sched-ext. Trixie experimented with it, but had some issues last time.
> > 
> > 
> > There is a sched-ext fedora/copr maintainer. The kernel itself should be ready fine for 6.9.
> > the scx-scheds package we can add to the copr, i guess.
> > linux-cachyos contains as default sched-ext (not sure about the copr here, but it should)
> 
> The problem we had last time was that the kernel-modules package ended up being 2 GB in size.
> 
> So in order to have sched-ext in the kernel, it needs to include this patch? https://github.com/CachyOS/kernel-patches/blob/master/6.9/sched/0001-sched-ext-eevdf.patch Or is it there without it?
> 
> Currently we include 0001-cachyos-base-all.patch and 0001-bore-cachy.patch

Correct, yes. But sched-ext requires to have debug enabled.

**Comment by andersrh** [comment]
We have added sched-ext to the stable branch kernel.
Closing this
